### PR TITLE
Use strict everywhere

### PR DESCRIPTION
**Pull request by Alaneor**
Added `use strict` declarations to all files in *archetype* and *lib/index.js*, for consistency.

I might have deleted a space or two in the process. Let me know if I should revert those space changes before this PR gets accepted. Thanks!

### CODE REVIEW

**Comment by Alaneor** [comment]
Just rebased on current master, resolving some conflicts. Any chance to have this merged? Thanks!

**Comment by tjwebb** [comment]
Conflicts again :/

**Comment by Alaneor** [comment]
Rebased again! Looks like AppVeyor sets `NODE_ENV = 'testing'` which currently breaks [this test](https://github.com/trailsjs/trails/blob/master/test/index.js#L94). Not sure if this is intentional or a default behaviour of AppVeyor. If intentional, I recommend moving env var configurations to the *.appveyor.yml* file so it's obvious for other people.

**Comment by jaumard** [comment]
I think AppVeyor set NODE_ENV = 'testing' by default. We can override it under `.appveyor.yml ` if needed. Or we can change the test because it doesn't test when NODE_ENV is already set. Don't know what is the best...

**Comment by Alaneor** [comment]
I would rather fix the test, so that it first saves the current value of NODE_ENV, deletes that value, creates new app, verifies desired behaviour and then restores the original NODE_ENV.

At any rate, I rebased again a few hours ago and now the tests pass 😕 .

**Comment by jaumard** [comment]
You're right I didn't notice all was green ^^ maybe AppVeyor is currently changing there env...

**Comment by tjwebb** [comment]
I've been re-running the AppVeyor builds because they were acting weird. And yes, we should move the NODE_ENV variable to the config files.

**Comment by tjwebb** [comment]
@Alaneor can you also submit fixes to generator-trails and generator-trailpack? We'll need to update them all at once

**Comment by Alaneor** [comment]
generator-trailpack - looks like [already done](https://github.com/trailsjs/generator-trailpack/commit/baa6c3a97c55645a230dfc3629e1950eae8f074b)
generator-trails - looks like [already done](https://github.com/trailsjs/generator-trails/commit/5dca5b9b7bddccfd8bd8ae78d11ae44bd255cc17)

Courtesy of @jaumard . :) If those are the files you had in mind @tjwebb then I guess we are good to go.

**Comment by tjwebb** [comment]
You are correct! Looks good, thanks.

**Pull request merged**
