### PR TITLE
Add issue stats badge to readme

### PR DESCRIPTION
**Pull request by nrempel**
Given that the main reason this project exists is because of stagnation in SailsJS, I thought it would be appropriate to boast issue-closing times.

https://github.com/vuejs/vue/ does this and it's really appealing to see sub 12hr ticket close times.

### CODE REVIEW

**Comment by nrempel** [comment]
Could also smack https://www.bithound.io/github/trailsjs/trails in there. All the badges!

**Comment by tjwebb** [comment]
Very nice, I hadn't used that before. Good idea :)

**Comment by tjwebb** [comment]
@nrempel we're holding off on bithound for now. It seems they don't yet support eslint 2.0, so it's marking all our builds as failed for no reason.

**Comment by nrempel** [comment]
:ok_hand:

**Pull request merged**
