### PR TITLE
Update ROADMAP.md

### PR DESCRIPTION
**Pull request by mikehostetler**
Adding snippet about Backlog, to be referenced in the contribution guidel

### CODE REVIEW

**Comment by tjwebb** [comment]
Good idea. I just created a matching milestone for the backlog: https://github.com/trailsjs/trails/milestones/Backlog. @mikehostetler do you mind throwing a link in there as well?

**Comment by mikehostetler** [comment]
Hmm, having two places to list `Backlog` items seems duplicative. The issue tracker solution makes more sense long term.  What do you think?  Here's the two options I see:

Solution 1: Kill the `Backlog` table on the Roadmap, point people to tag issues with the Backlog milestone in the Queue.  Pro's: This pattern could be followed across all Trails repo's. Con's: Disparate issue sizes makes the queue unwieldy.

Solution 2: Keep the `Backlog` table in the Roadmap to track big feature requests, use the `Backlog` Milestone to track smaller backlog items.  Pro's: Better management of different sized backlog items. Con's: Managing multiple queues is generally a bad idea.

**Comment by tjwebb** [comment]
In the previous roadmap sections, I list some high level objectives and then link to the milestone for specific issues. For the Backlog, we could "promote" certain things we're more interested in seeing done, even if we can't schedule the time to do them ourselves.

**Comment by mikehostetler** [comment]
Ok, cool. I'll link it up!

**Comment by tjwebb** [comment]
Hey @mikehostetler if you can wrap this up I'll go ahead and merge it in.

**Comment by mikehostetler** [comment]
@tjwebb Added!

**Pull request merged**
