### PR TITLE
splitting out handlebars and jade configs

### PR DESCRIPTION
**Pull request by weyj4**
Is this a good way to do this? Literally the only change is the one line,
engine: require('whatever').

I've updated the generator to configure this, but maybe there's a simpler solution. Or, we could just make the user type that line themselves ;)

### CODE REVIEW

**Comment by jaumard** [comment]
I think this is to much modification for a small thing. Why not just have under `config/views.js` something like : 

```
/**
 * Views Configuration
 * (app.config.views)
 *
 * @see http://trailsjs.io/doc/config/views.js
 */
module.exports = {
    engine: '<%= engine %>'
}
```
Like this the generator will replace with the template engine choose by the user. It's done like this under `generator-trails` and `generator-trailpack` for controllers/models/policies and services.

And same have to be done for web server because for now `trailpack-hapi` is hard coded under `config/main.js`

**Comment by weyj4** [comment]
Agreed, I'll update this PR.

**Comment by jaumard** [comment]
Cool :) also need to update this one https://github.com/trailsjs/generator-trails/pull/11 then. Can you do it too ?

**Comment by tjwebb** [comment]
fwiw, jade is now called "pug"

**Pull request closed without merging**
