### PR TITLE
Update dependencies archetype

### PR DESCRIPTION
**Pull request by jaumard**
#### Description
Update dependencies archetype

#### Issues
- related to https://github.com/trailsjs/trails/issues/195

### CODE REVIEW

**Comment by jaumard** [comment]
also related to https://github.com/trailsjs/generator-trails/issues/58

**Comment by jaumard** [comment]
The test who is failing is this one https://travis-ci.org/trailsjs/trails/jobs/136131444#L246 but it is too dependent on the environment and perf on travisCI can be bad

**Comment by jaumard** [comment]
@tjwebb did you know why we can't restart build on travisCI for Trails ? On other repo I can...

**Comment by scott-wyatt** [comment]
Strange that this is only failing on Node 4 on mac on Travis-Ci... could we retry the build? (unable to do it on my end)

**Comment by scott-wyatt** [comment]
@jaumard, if you close and re-open this, it might trigger another build attempt.

**Comment by jaumard** [comment]
Nice catch ^^ we'll see if it pass now :) thanks

**Comment by scott-wyatt** [comment]
yay! It passes, @trailsjs/maintainers review please?

**Comment by jaumard** [comment]
@trailsjs/maintainers need a new version on NPM, lot of users still use the beta because `npm update` didn't update to last deps.

**Pull request merged**
