### PR TITLE
Fix pack import into trailsApp and add i18n default config file

### PR DESCRIPTION
**Pull request by jaumard**
Fix undefined `this.app.packs` from https://github.com/trailsjs/trails/issues/32

### CODE REVIEW

**Comment by tjwebb** [comment]
@jaumard now it's set in two places: https://github.com/jaumard/trails/blob/master/index.js#L87

We should figure out the correct place to set `this.packs` and do it only once.

**Comment by jaumard** [comment]
You're right I miss this one ! I will look what can go wrong with the first one.

**Comment by jaumard** [comment]
Ok I put some breakpoints and the `validate` of `Trailpack` is called before the `validateTrailpacks` of `TrailsApp` that's why `this.app.packs` is undefined.
```
validateTrailpacks (packs) {
    return Promise.all(packs.map(pack => pack.validate()))//Call first validate
      .then(() => {
        this.packs = lib.Util.getTrailpackMapping(packs)//Then copy packs to app 
        console.log(this.packs)
        this.log.verbose('Trailpacks: All Validated.')
        this.emit('trailpack:all:validated')
      })
      .catch(err => this.stop(err))
  }
```
Now I understand why `packs` is undefined. It make sens to me to use `this.app.config.main.packs` on `validate` function. Tell me what do you think. I can update my PR or delete it if we want to let like this.

**Comment by jaumard** [comment]
I just remove duplicate copy of packs and add default i18n config file to prevent Trails to crash :
```
TypeError: Cannot read property 'compatibilityAPI' of undefined
    at t.u.value (/Development/Trails/testapp/node_modules/trailpack-core/node_modules/i18next/bin/index.js:2:3182)
    at /Development/Trails/testapp/node_modules/trailpack-core/lib/i18n.js:6:15
    at Object.init (/Development/Trails/testapp/node_modules/trailpack-core/lib/i18n.js:5:12)
    at Core.initialize (/Development/Trails/testapp/node_modules/trailpack-core/index.js:34:21)
    at /Development/Trails/testapp/node_modules/trails/lib/trailpack.js:46:26
    at process._tickDomainCallback (node.js:411:9)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by jaumard** [comment]
Close this PR cause not needed anymore i18n is under core archetype

**Pull request closed without merging**
