### PR TITLE
allow to disable trailpacks on config

### PR DESCRIPTION
**Pull request by jaumard**
update deps

Allowed syntax
```
      trailpacks: {
        disabled: ['repl']
      }
```

### CODE REVIEW

**Comment by jaumard** [comment]
@scott-wyatt finally here it is :D lol
@tjwebb don't know if you want `trailpack` or `trailpacks` so I choose `trailpacks` as it sound more logic

**Comment by scott-wyatt** [comment]
I'm glad there is progress here! However, I have a small issue.  What else does config/trailspacks even do? All I ever seen it used for is this disabled key that takes an array. Then there is the weird thing where you use only the trailing part of the pack name. So to disable `trailpack-repl` you just use `repl`.  Then there is a follow up.  As trailpacks become more dependent on each other is it possibly necessary for a trailpack to know it's been disabled?  It would be particularly useful if you could change the state of a trailpack on the fly which would require trailpacks have a `disable` method in the constructor.

**Comment by jaumard** [comment]
As I know `config/trailpacks` do only this for now.
When trailpack are load you can use them without the `trailpack` prefix, we can allow `trailpack-repl` under `config/trailpacks` and under the hood remove the prefix if you prefer. 
For example if I disable `repl`, I know it's disabled because `app.packs.repl` doesn't exist. 

But normally you should know very quickly if there a dependency problem because your tests will fail ^^. 

Trailpack already had an `unload` method that could do the job, a `disable` method will duplicate the logic.

Trailpack are created to be static not to be dynamically load/unload because for this we should use `trailpack-microservices` witch for now doesn't exist lol 
Normally you'll not need to enable/disabled a trailpack dynamically or it's shouldn't be a trailpack but a microservice

**Comment by scott-wyatt** [comment]
@jaumard Totally satisfied with that answer and this PR :-)

**Comment by scott-wyatt** [comment]
@tjwebb @jaumard, is this okay to be merged and published?

**Comment by jaumard** [comment]
If everyone is ok with this ready to merge for me :) can't do it I don't have rights ^^

**Comment by scott-wyatt** [comment]
@konstantinzolotarev, could you take a look at this?

**Comment by konstantinzolotarev** [comment]
@scott-wyatt I'm ok with this change. But in last talk with @tjwebb about this. There was something weird. I'd prefer to wait him.

**Comment by tjwebb** [comment]
Yea, the reason I didn't originally write this feature is because if a Trailpack is "disabled", but still loaded from the `require()` statement, then it's still part of the application, loaded into the require cache and all these other places. On the off chance (a badly designed module) could cause side-effects by being required (if there's logic outside the Trailpack class definition), I think we should find a way to avoid loading the module at all, instead of loading it first and then disabling it.

Currently, I'm just redefining the whole trailpack list in the `env` files. e.g. for production, I just re-write the whole packs array, and remove `trailpack-repl`. This isn't a great developer experience, but it has the advantage of being correct. We should try to preserve this functionality, but make it easier for the developer.

**Comment by tjwebb** [comment]
yea, here's one example. `trailpack-mapnik` requires mapnik, which does all kinds of shit without needing to be constructed: https://github.com/mapnik/node-mapnik/blob/master/lib/mapnik.js. It's talking to the file system, it's invoking methods on some binary binding that it has with the system "mapnik" lib. Even if I disable trailpack-mapnik using the method in this PR, all that stuff is still happening.

**Comment by scott-wyatt** [comment]
So i've started implementing what @tjwebb suggested which is to reconfig the entire main packs for each environment.  This really does give you a ton of control.

**Comment by tjwebb** [comment]
@scott-wyatt can you reference the branch you've been working on so that we can track there?

Closing.

**Comment by scott-wyatt** [comment]
Sorry @tjwebb, it's not a branch, it's what I am doing now in personal projects. (overriding the main.packs config for each environment)

**Pull request closed without merging**
